name: FTP Deploy

on:
  push:
    branches:
      - main  # Change this if you want to deploy from a different branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This checks out your repository code

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5  # Use the latest version available
      with:
        server: ftpupload.net  # Your FTP server URL
        username: ${{ secrets.FTPUSERNAME }}  # Use secrets for security
        password: ${{ secrets.FTPPASSWORD }}  # Use secrets for security
      
        server-dir: '/htdocs/'  # The directory on the server to deploy to
