name: FTP Deploy

on:
  push:
    branches:
      - main  # Change this if you want to deploy from a different branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This checks out your repository code

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.4  # Use the latest version available
      with:
        server: ftp://ftpupload.net  # Your FTP server URL
        username: ${{ secrets.FTP_USERNAME }}  # Use secrets for security
        password: ${{ secrets.FTP_PASSWORD }}  # Use secrets for security
        local-dir: './'  # The local directory to deploy (can adjust as needed)
        server-dir: '/htdocs'  # The directory on the server to deploy to
